openapi: "3.0.3"
info:
  title: BPM Api
  description: |
    Description for the **BPM Api**
  termsOfService: https://github.com/L-Applin/bpm
  contact:
    name: L-Applin
    url: https://github.com/L-Applin/bpm
    email: no-email-support-for-open-source-project@do-not-contact-by-email.com
  license:
    name: Apache 2.0
    url: https://github.com/L-Applin/bpm/blob/main/LICENSE
  version: 0.0.0

paths:
  /api/projects:
    get:
      summary: returns information about all projects managed by BPM
      responses:
        200:
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/responses/ProjectInfo'

  /api/projects/{project-name}:
    get:
      summary: returns information about the specified project
      parameters:
        - in: path
          name: project-name
          description: the project to get information about
          schema:
            type: string
          required: true
      responses:
        200:
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/responses/ProjectInfo'
        404:
          description: project not found

  /api/{project-name}/create-pipeline:
    post:
      summary: Create a new pipeline in the specified project
      parameters:
        - in: path
          name: 'project-name'
          description: the project in which to add the pipeline
          schema:
            type: string
          required: true
      requestBody:
        description: the structure of the pipeline to add
        content:
          application/octet-stream:
            schema:
              type: string
              format: base64
      responses:
        201:
          description: successful


components:
  schemas:
    ProjectInfo:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/ProjectInfoItem'
    ProjectInfoItem:
      type: object
      properties:
        name:
          type: string
        pipelines:
          type: array
          items:
            type: string
  responses:
    ProjectInfo:
      description: Information about a project managed by BPM
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectInfo'

