FROM ubuntu

RUN apt-get update && apt-get -y install sudo
RUN sudo apt-get -y install iputils-ping

RUN mkdir -p bpm/$BPM_INPUT
RUN mkdir -p bpm/$BPM_OUTPUT

VOLUME "bpm"

ENTRYPOINT [ "/bin/bash", "-c", "while true; do ping -i 10 8.8.8.8 &> /dev/null ; done"]